2023-09-27 17:48:38,176 ERROR Internal Server Error: /news/35/ C:\Users\kuchinsk\file\pws\D\newspaper\venv\lib\site-packages\django\utils\log.py (<class 'ZeroDivisionError'>, ZeroDivisionError('division by zero'), <traceback object at 0x0000019E09142F00>)
Traceback (most recent call last):
  File "C:\Users\kuchinsk\file\pws\D\newspaper\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\kuchinsk\file\pws\D\newspaper\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\kuchinsk\file\pws\D\newspaper\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\kuchinsk\file\pws\D\newspaper\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\kuchinsk\file\pws\D\newspaper\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\kuchinsk\file\pws\D\newspaper\venv\lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
  File "C:\Users\kuchinsk\file\pws\D\newspaper\newspaper\news\views.py", line 64, in get_object
    1/0
ZeroDivisionError: division by zero
2023-09-27 17:48:38,181 ERROR "GET /news/35/ HTTP/1.1" 500 98641 C:\Users\kuchinsk\file\pws\D\newspaper\venv\lib\site-packages\django\core\servers\basehttp.py None
